services:
  notes:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: notes
    environment:
      DATA_PATH: /app_data
      NODE_EXTRA_CA_CERTS: /home/node/certs/localhost.crt
      SW__ALLOWED_DOMAINS: localhost # 192.168.X.X notes.example.com 
      SW__APP_ID: notes
      TZ: America/Los_Angeles
    image: theonewhoknocks/notes
    ports:
      # Map Local port to the Container's exposed port
      - "3000:3000"
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      - "${PWD}/certs:/home/node/certs"
      - type: bind
        source: "${PWD}/e2e/mnt/data"
        target: "/app_data"
  
  notes-dev:
    extends: notes
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: notes-dev
    environment:
      NODE_ENV: development
    ports:
      # browserSync
      - "3001:3001" # proxied App
      - "3002:3002" # not sure, but I think this is for WS connections
      - "3003:3003" # bsync GUI
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
