version: "3"

services:
  e2e-cypress:
    # command: 'cypress run --browser chrome'
    container_name: e2e-notes
    depends_on:
      - notes
    environment:
      ## Cypress vars
      CYPRESS_BASE_URL: "${CYPRESS_BASE_URL}"
      # DEBUG: cypress:server:browsers:electron # view Electron internal logging
      # ELECTRON_ENABLE_LOGGING: 1 # view console logs from Browser (headless)
      ## Test vars
      # CYPRESS__MOCK_TIME: "${MOCK_TIME}"
      # CYPRESS__PATHS__MOCKS: /repo/e2e/cypress/fixtures
    hostname: cypresstests
    image: cypress/included:9.3.0
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ports:
      - "9001:3000"
    privileged: true
    user: "${CURR_UID}:${CURR_GID}"
    working_dir: /repo/e2e
    volumes:
      - "${PWD}/dist/constants.js:/repo/e2e/mnt/constants.js"
      - "${PWD}/e2e:/repo/e2e"
      - type: bind
        source: "${PWD}/e2e/mnt/data"
        target: "/repo/e2e/cypress/fixtures"
  
  notes:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: notes
    environment:
      DATA_PATH: /app_data
      NODE_EXTRA_CA_CERTS: /home/node/certs/localhost.crt
      TZ: America/Los_Angeles
    image: theonewhoknocks/notes
    ports:
      # Map Local port to the Container's exposed port
      - "3000:3000"
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      - "${PWD}/certs:/home/node/certs"
      - type: bind
        source: "${PWD}/e2e/mnt/data"
        target: "/app_data"
  
  notes-dev:
    extends: notes
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: notes-dev
    environment:
      NODE_ENV: development
    ports:
      # browserSync
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
